apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bombastic-api
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bombastic-api
    app.kubernetes.io/part-of: trustification
  name: bombastic-api
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: bombastic-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: bombastic-api
    spec:
      containers:
      - env:
        - name: REGION
          value: eu-west-1
        - name: RUST_LOG
          value: info
        - name: INFRASTRUCTURE_ENABLED
          value: "true"
        image: quay.io/redhat-user-workloads/ulilleen-tenant/trustification/bombastic-api@sha256:1bf4c139263522554b4884164a227d8053a2b10f644474878f5783071cda3a14
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
