apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bombastic-api
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bombastic-api
    app.kubernetes.io/part-of: trustification
  name: bombastic-api
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: bombastic-api
status:
  loadBalancer: {}
